# Generated by Django 2.1.2 on 2019-04-29 07:49

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagecluster',
            name='devices',
            field=common.models.JsonTextField(blank=True, null=True, verbose_name='Devices'),
        ),
    ]
