# Generated by Django 2.1.2 on 2019-04-29 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_storage', '0002_storagecluster_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagecluster',
            name='devices',
        ),
    ]
