# Generated by Django 2.1.2 on 2019-05-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pod',
            name='project',
        ),
        migrations.RemoveField(
            model_name='service',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='pods',
            field=models.ManyToManyField(to='openshift_client.Pod'),
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(to='openshift_client.Service'),
        ),
    ]
