# Generated by Django 2.1.2 on 2019-05-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_client', '0002_auto_20190506_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pod',
            name='restarts',
        ),
        migrations.RemoveField(
            model_name='pod',
            name='status',
        ),
    ]
