# Generated by Django 2.1.2 on 2019-05-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_base', '0007_auto_20190506_0826'),
        ('openshift_client', '0004_project_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenshiftNode',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('openshift_base.node',),
        ),
    ]
