# Generated by Django 2.1.2 on 2019-05-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_client', '0005_openshiftnode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenshiftNode',
        ),
    ]
