# Generated by Django 2.1.2 on 2019-05-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_base', '0006_deployexecution_current_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='message',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='status',
            field=models.CharField(choices=[('Ready', 'Ready'), ('NotReady', 'NotReady')], default='NotReady', max_length=64),
        ),
    ]
