# Generated by Django 2.1.2 on 2019-04-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0002_openshiftcluster_storages'),
    ]

    operations = [
        migrations.AddField(
            model_name='openshiftcluster',
            name='connect_config',
            field=models.TextField(blank=True, null=True),
        ),
    ]
