# Generated by Django 2.1.2 on 2019-04-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0003_openshiftcluster_connect_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='openshiftcluster',
            name='auth',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
