# Generated by Django 2.1.2 on 2019-05-06 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0004_openshiftcluster_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openshiftcluster',
            name='storages',
        ),
    ]
