# Generated by Django 2.1.2 on 2019-05-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0005_remove_openshiftcluster_storages'),
        ('openshift_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openshiftcluster',
            name='projects',
            field=models.ManyToManyField(to='openshift_client.Project'),
        ),
    ]
