# Generated by Django 2.1.2 on 2019-05-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0006_openshiftcluster_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='openshiftcluster',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'running'), ('STOP', 'stop'), ('INSTALLING', 'installing'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=128),
        ),
    ]
