# Generated by Django 2.1.2 on 2019-05-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_client', '0002_auto_20190506_0748'),
        ('openshift_api', '0007_openshiftcluster_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='openshiftcluster',
            name='pods',
            field=models.ManyToManyField(to='openshift_client.Pod'),
        ),
        migrations.AddField(
            model_name='openshiftcluster',
            name='services',
            field=models.ManyToManyField(to='openshift_client.Service'),
        ),
    ]
