# Generated by Django 2.1.2 on 2019-05-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0010_auto_20190514_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openshiftcluster',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'running'), ('INSTALLING', 'installing'), ('UNKNOWN', 'unknown'), ('ERROR', 'error'), ('WARNING', 'warning')], default='UNKNOWN', max_length=128),
        ),
    ]
